apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gg-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/just2courageous/gg-gitops.git
    targetRevision: main
    path: apps/demo

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
