apiVersion: v1
kind: Pod
metadata:
  name: load-tester
  namespace: demo
  labels:
    app: load-tester
spec:
  restartPolicy: Never
  containers:
  - name: looper
    image: alpine:3.19
    command: ["sh", "-c"]
    args:
    - |
      while true; do
        wget -q -O- http://demo-app.demo.svc.cluster.local > /dev/null
      done
